# Generated by Django 4.0 on 2022-02-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=254, unique=True)),
                ('totalmatch', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ('-totalmatch',),
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='API.search')),
            ],
            options={
                'ordering': ('-match',),
            },
        ),
    ]
